# Dependencies
markdown:         redcarpet
highlighter:      pygments
encoding: 		  utf-8


# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            김로그
tagline:          ''
description:      '2016.01'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'WJ'
  url:            #https://twitter.com/mdo

paginate:         5
comments:		  true

# Custom vars
github:
  repo:           https://github.com/gnujoow
