permalink:           pretty

# Setup
title:               김로그
tagline:             ''
description:         "머신러닝을 공부하고 있는 백수의 블로그"
url:                 http://gnujoow.github.io/
baseurl:             ''

#paginate
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# About/contact
author:
  name:              gnujoow
  url:               http://github.com/gnujoow
  email:             gnujoow.kim@gmail.com

# Custom vars
version:             1.0.0
