# Dependencies
markdown:         redcarpet
highlighter:      pygments
encoding: 		  utf-8


# Permalinks
permalink:        pretty

# Setup
title:            김로그
tagline:          ''
description:      '2016.01'
url:              http://gnujoow.github.io/
description: "머신러닝을 공부하고 있는 백수의 블로그"

#
author:
  name:           'WJ'
  url:            #https://twitter.com/mdo

paginate:         5

# Custom vars
github:
  repo:           https://github.com/gnujoow
