permalink:           pretty

# Setup
title:               김로그
tagline:             '개발 잘 하고 싶다'
description:         "happy coding :)"
url:                 http://gnujoow.github.io/
baseurl:             ''

#paginate
gems: [jekyll-paginate]
paginate: 20
paginate_path: "page:num"

# About/contact
author:
  name:              gnujoow
  url:               http://github.com/gnujoow
  email:             gnujoow.kim@gmail.com
