permalink:           pretty

# Setup
title:               김로그
tagline:             '개발 잘 하고 싶다'
description:         "happy coding :)"
url:                 http://gnujoow.github.io/
baseurl:             ''

gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-timeago

# paginate
paginate: 20
paginate_path: "page:num"

# time ago
jekyll_timeago:
  depth: 1

# About/contact
author:
  name:              gnujoow
  url:               http://github.com/gnujoow
  email:             gnujoow.kim@gmail.com
