# Dependencies
markdown:         redcarpet
highlighter:      pygments
encoding: 		  utf-8


# Permalinks
permalink:        pretty

# Setup
title:            김로그
tagline:          ''
description:      '2016.01'
url:              /
baseurl:          /

author:
  name:           'WJ'
  url:            #https://twitter.com/mdo

paginate:         5

# Custom vars
github:
  repo:           https://github.com/gnujoow
