# Dependencies
markdown:         redcarpet
highlighter:      pygments
encoding: 		  utf-8


# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            김로그
tagline:          'A Jekyll blog by gnujoow'
description:      '2016.01'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
github:
  repo:           https://github.com/gnujoow
